"""
Standard WAT practice words for SSB - curated list of common words
used in real tests (positive, neutral, negative, defence-related).
"""

WAT_WORDS = [
    # Common core set
    "Courage", "Fear", "Leader", "Failure", "Success", "Duty", "Mother", "War",
    "Death", "Life", "Money", "Friend", "Enemy", "Kill", "Help", "Defeat",
    "Victory", "Discipline", "Responsibility", "Initiative", "Team", "Alone",
    "Stress", "Hope", "Anger", "Peace", "Gun", "Border", "Nation", "Army",
    "Navy", "Airforce", "Officer", "Soldier", "Challenge", "Hardwork", "Plan",
    "Organize", "Motivate", "Desire", "Aim", "Achieve", "Progress", "Weak",
    "Strong", "Brave", "Honest", "Loyalty", "Respect", "Trust", "Doubt",
    "Confidence", "Risk", "Safety", "Danger", "Rescue", "Accident", "Fire",
    "Water", "Mountain", "Journey", "Home", "Family", "Child", "Education",
    "Knowledge", "Book", "Exam", "Time", "Future", "Past", "Dream", "Ambition",
    "Sacrifice", "Patriotism", "Freedom", "Justice", "Corruption", "Bribe",
    "Truth", "Lie", "Quarrel", "Discuss", "Agree", "Disagree", "Attack",
    "Defend", "Escape", "Fight", "Guts", "Award", "Praise", "Blame", "Mistake",
    "Learn", "Improve", "Change", "Adapt", "Crisis", "Calm", "Panic", "Focus",
    "Decision", "Command", "Obey", "Lead", "Follow", "Unity", "Division",
    "Poverty", "Wealth", "Hunger", "Health", "Disease", "Cure", "Doctor",
    "Teacher", "Student", "Village", "City", "Rural", "Urban", "Technology",
    "Tradition", "Modern", "Youth", "Old", "Experience", "Wisdom", "Foolish",
    "Smart", "Lazy", "Active", "Passive", "Positive", "Negative", "Optimism",
    "Pessimism", "Love", "Hate", "Kindness", "Cruelty", "Helpful", "Selfish",
    "Generous", "Greedy", "Patience", "Impatience", "Perseverance", "Quit",
    "Continue", "Start", "End", "Begin", "Finish", "Incomplete", "Complete",
    "Perfect", "Imperfect", "Beautiful", "Ugly", "Clean", "Dirty", "Order",
    "Chaos", "System", "Confusion", "Clear", "Vague", "Certain", "Uncertain",
    "Sure", "Doubtful", "Believe", "Doubt", "Faith", "Religion", "God",
    "Prayer", "Action", "Thought", "Word", "Deed", "Mind", "Body", "Soul",
    "Character", "Personality", "Attitude", "Behaviour", "Habit", "Routine",
    "Discipline", "Punctual", "Late", "Early", "Fast", "Slow", "Quick",
    "Sudden", "Gradual", "Immediate", "Delay", "Urgent", "Important",
    "Trivial", "Priority", "Ignore", "Notice", "Observe", "Overlook",
    "Careful", "Careless", "Alert", "Sleepy", "Awake", "Tired", "Energetic",
    "Exhausted", "Rest", "Work", "Play", "Game", "Sport", "Competition",
    "Cooperate", "Compete", "Win", "Lose", "Draw", "Fair", "Unfair",
    "Rules", "Break", "Follow", "Law", "Crime", "Punishment", "Reward",
    "Justice", "Injustice", "Right", "Wrong", "Moral", "Immoral", "Ethical",
    "Unethical", "Principle", "Value", "Belief", "Opinion", "Fact", "Rumour",
    "News", "Media", "Social", "Media", "Internet", "Phone", "Message",
    "Call", "Meet", "Talk", "Listen", "Speak", "Silent", "Noise", "Quiet",
    "Loud", "Soft", "Hard", "Soft", "Rough", "Smooth", "Sharp", "Blunt",
    "Knife", "Sword", "Shield", "Helmet", "Uniform", "March", "Parade",
    "Training", "Camp", "Mission", "Operation", "Strategy", "Tactics",
    "Intelligence", "Surveillance", "Security", "Threat", "Protect",
    "Defend", "Attack", "Advance", "Retreat", "Hold", "Position", "Post",
    "Checkpoint", "Border", "Line", "Control", "Area", "Zone", "Sector",
    "Company", "Battalion", "Brigade", "Division", "Corps", "Command",
    "Headquarters", "Base", "Camp", "Tent", "Barrack", "Mess", "Canteen",
    "Ration", "Ammunition", "Weapon", "Rifle", "Pistol", "Grenade", "Bomb",
    "Mine", "Tank", "Aircraft", "Ship", "Submarine", "Missile", "Radar",
    "Communication", "Radio", "Signal", "Code", "Cipher", "Secret", "Open",
    "Covert", "Overt", "Day", "Night", "Dawn", "Dusk", "Morning", "Evening",
    "Night", "Dark", "Light", "Shadow", "Sun", "Moon", "Star", "Sky",
    "Cloud", "Rain", "Storm", "Flood", "Drought", "Earthquake", "Disaster",
    "Relief", "Aid", "Help", "Support", "Assist", "Rescue", "Evacuate",
    "Shelter", "Food", "Water", "Medicine", "Supply", "Logistics",
    "Transport", "Vehicle", "Truck", "Jeep", "Helicopter", "Plane", "Train",
    "Road", "Bridge", "River", "Hill", "Valley", "Forest", "Desert",
    "Jungle", "Mountain", "Pass", "Route", "Path", "Track", "Trail",
    "Map", "Compass", "GPS", "Navigation", "Direction", "North", "South",
    "East", "West", "Left", "Right", "Forward", "Backward", "Up", "Down",
]

# Ensure unique and clean
WAT_WORDS = list(dict.fromkeys([w.strip().title() for w in WAT_WORDS if w.strip()]))
